// <auto-generated />
using System;
using InterviewScheduler.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809061419_EnableUnrestrictedSchedulingForAppointmentTypes")]
    partial class EnableUnrestrictedSchedulingForAppointmentTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("ContactId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.AppointmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAfterHoursScheduling")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowWeekendScheduling")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BufferTimeAfterMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BufferTimeBeforeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumAdvanceBookingDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumAdvanceBookingHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinorMessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireStrictBufferTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchedulingPriority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppointmentTypes");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadOfHouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeadOfHouseId");

                    b.HasIndex("SpouseId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Leader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoogleCalendarId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Leaders");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Appointment", b =>
                {
                    b.HasOne("InterviewScheduler.Core.Entities.AppointmentType", "AppointmentType")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewScheduler.Core.Entities.Contact", "Contact")
                        .WithMany("Appointments")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewScheduler.Core.Entities.Leader", "Leader")
                        .WithMany("Appointments")
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterviewScheduler.Core.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentType");

                    b.Navigation("Contact");

                    b.Navigation("Leader");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.AppointmentType", b =>
                {
                    b.HasOne("InterviewScheduler.Core.Entities.User", "User")
                        .WithMany("AppointmentTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Contact", b =>
                {
                    b.HasOne("InterviewScheduler.Core.Entities.Contact", "HeadOfHouse")
                        .WithMany("HouseholdMembers")
                        .HasForeignKey("HeadOfHouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InterviewScheduler.Core.Entities.Contact", "Spouse")
                        .WithOne()
                        .HasForeignKey("InterviewScheduler.Core.Entities.Contact", "SpouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InterviewScheduler.Core.Entities.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadOfHouse");

                    b.Navigation("Spouse");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Leader", b =>
                {
                    b.HasOne("InterviewScheduler.Core.Entities.User", "User")
                        .WithMany("Leaders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.AppointmentType", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Contact", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HouseholdMembers");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.Leader", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("InterviewScheduler.Core.Entities.User", b =>
                {
                    b.Navigation("AppointmentTypes");

                    b.Navigation("Appointments");

                    b.Navigation("Contacts");

                    b.Navigation("Leaders");
                });
#pragma warning restore 612, 618
        }
    }
}
